### ISSUE TITLE
Moodle 3.1 and Foundation 6?

### ISSUE THREAD

**Issue by KSLaring** [thedannywahl/foundation4-for-moodle2#1]
Hi Danny,

This looks interesting, but out of date. Any chance you might bump this to include Foundation 6 for use with Moodle 3.1?

Cheers,
Haakon

**Comment by thedannywahl** [comment]
Hi, I'm going to say _probably_ not as foundation 6 requires a different semantic layout and moodle has since embraced bootstrap (moodle 3.2).  At the time that I wrote this they hadn't had a specific front-end framework in place, but only provided methods for overriding the output in specific ways allowing the use of foundation.  Now to do it you'll have to first remove bootstrap, and then reimplement foundation.  too much work IMO.
